apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-15T10:39:50Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "7848"
  uid: 5c0c6c3c-a39a-4515-8804-0c5a87e48f3c
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.99.164.214
  clusterIPs:
  - 10.99.164.214
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31508
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
